---
title: "Stability for Multispecies Competition with Delayed Maturity"
author: "Geoffrey R. Hosack, Maud El-Hachem, Nicholas J. Beeton"
date: "2024-11-26"
---

<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{MultiSppDelayStability-vignette}
-->



```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = TRUE,
  comment = "#>"
)
```

This vignette provides the reproducible code for the numerical stability analysis appearing in ``Stability of difference equations with interspecific density dependence, competition, and maturation delays''.

```{r example}

# equilibrium relative abundance -----------------------------------------------
x.bar <- c(907, 1123, 625)/2   # Pombi et al (2017)
names(x.bar) <- c("Aa", "Ac", "Ag")

# relative abundances
p.star <- round(x.bar/sum(x.bar), 2)

# niche overlap estimate (Pombi et al. 2017) -----------------------------------
Ap <- diag(3)
Ap[lower.tri(Ap)] <- Ap[upper.tri(Ap)] <- c(0.717, 0.562, 0.492)

# density independent parameters (North and Godfray 2018) ----------------------
z <- rep(0.125, 3)
sigma <- 1 - z
lambda <- 9/2

# vector of density independent parameters
b <- (lambda - z)/z

# Jacobians --------------------------------------------------------------------

## Jacobian based on abundances ------------------------------------------------
Jfun <- function(xbar, A, delta = 10) {

  x <- xbar

  # build Jacobian matrix
  n.age <- delta + 1 # include age zero
  J <- matrix(0, nrow = 3*(delta + 1), ncol = 3*(delta + 1))

  # lags
  J[2:n.age, 1:(n.age - 1)] <-
    J[(n.age + 2):(2*n.age), (n.age + 1):(2*n.age - 1)] <-
    J[(2*n.age + 2):(3*n.age), (2*n.age + 1):(3*n.age - 1)] <-
    diag(delta)

  # density independent adult mortality
  J[n.age, n.age] <- sigma[1]
  J[2*n.age, 2*n.age] <- sigma[2]
  J[3*n.age, 3*n.age] <- sigma[3]

  # density dependence
  # rowwise
  # species 1
  J[1, n.age] <- z[1]*(1 - z[1]*A[1, 1]*x[1]/(lambda*q[1]))
  J[1, 2*n.age] <- -z[1]^2*A[1, 2]*x[1]/(lambda*q[1])
  J[1, 3*n.age] <- -z[1]^2*A[1, 3]*x[1]/(lambda*q[1])
  # species 2
  J[n.age + 1, n.age] <- -z[2]^2*A[2, 1]*x[2]/(lambda*q[2])
  J[n.age + 1, 2*n.age] <- z[2]*(1 - z[2]*A[2, 2]*x[2]/(lambda*q[2]))
  J[n.age + 1, 3*n.age] <- -z[2]^2*A[2, 3]*x[2]/(lambda*q[2])
  # species 3
  J[2*n.age + 1, n.age] <- -z[3]^2*A[3, 1]*x[3]/(lambda*q[3])
  J[2*n.age + 1, 2*n.age] <- -z[3]^2*A[3, 2]*x[3]/(lambda*q[3])
  J[2*n.age + 1, 3*n.age] <- z[3]*(1 - z[3]*A[3, 3]*x[3]/(lambda*q[3]))

  J

}

## Jacobian based on relative abundance  ---------------------------------------

Jpfun <- function(p2, p3, A, delta = 10) {

  # proportions
  if (p2 < 0 || p3 < 0) stop("req positive proportions")
  if (p2 > 1 || p3 > 1) stop("req proportions lt one")

  p1 <- 1 - p2 - p3

  x <- c(1, p2/p1, p3/p1)

  # build Jacobian matrix
  n.age <- delta + 1 # include age zero
  J <- matrix(0, nrow = 3*(delta + 1), ncol = 3*(delta + 1))

  # lags
  J[2:n.age, 1:(n.age - 1)] <-
    J[(n.age + 2):(2*n.age), (n.age + 1):(2*n.age - 1)] <-
    J[(2*n.age + 2):(3*n.age), (2*n.age + 1):(3*n.age - 1)] <-
    diag(delta)

  # density independent adult mortality
  J[n.age, n.age] <- sigma[1]
  J[2*n.age, 2*n.age] <- sigma[2]
  J[3*n.age, 3*n.age] <- sigma[3]

  # density dependence
  # rowwise
  # species 1
  J[1, n.age] <- z[1]*(1 - ((lambda - z[1])/lambda)*A[1, 1]*x[1]/(A[1, ]%*%x))
  J[1, 2*n.age] <- -z[1]*((lambda - z[1])/lambda)*A[1, 2]*x[1]/(A[1, ]%*%x)
  J[1, 3*n.age] <- -z[1]*((lambda - z[1])/lambda)*A[1, 3]*x[1]/(A[1, ]%*%x)
  # species 2
  J[n.age + 1, n.age] <- -z[2]*((lambda - z[2])/lambda)*A[2, 1]*x[2]/(A[2, ]%*%x)
  J[n.age + 1, 2*n.age] <- z[2]*(1 - ((lambda - z[2])/lambda)*x[2]/(A[2, ]%*%x))
  J[n.age + 1, 3*n.age] <- -z[2]*((lambda - z[2])/lambda)*A[2, 3]*x[2]/(A[2, ]%*%x)
  # species 3
  J[2*n.age + 1, n.age] <- -z[3]*((lambda - z[3])/lambda)*A[3, 1]*x[3]/(A[3, ]%*%x)
  J[2*n.age + 1, 2*n.age] <- -z[3]*((lambda - z[3])/lambda)*A[3, 2]*x[3]/(A[3, ]%*%x)
  J[2*n.age + 1, 3*n.age] <- z[3]*(1 - ((lambda - z[3])/lambda)*x[3]/(A[3, ]%*%x))

  J

}

# Pianka niche overlap estimate ------------------------------------------------

## simulation ------------------------------------------------------------------

# Pianka
A <- Ap
q <- diag(z)%*%solve(diag(lambda - z))%*%A%*%x.bar
solve(A)%*%diag(lambda - z)%*%solve(diag(z))%*%q - x.bar

all.equal(Jfun(x.bar, A), Jpfun(p.star[2], p.star[3], A))

J <- Jfun(x.bar, A)
summary(abs(eigen(J)$values))

set.seed(505)
# initial condition: random deviation from overall average
xi0 <- rlnorm(3, log(x.bar), sdlog = 1)

xi0/x.bar

Q <- diag(c(q))
N <- 365
xi <- matrix(NA, nrow = 3, ncol = N)
xi[ , 1:10] <- matrix(xi0, nrow = 10, ncol = 3)
for (tt in 11:N) {
  xi[ , tt] <- diag(sigma)%*%xi[ , tt - 1] + 
    + solve(diag(c(1 + solve(Q)%*%A%*%xi[ , tt - 10])))%*%xi[ , tt - 10]*lambda
}

png("nicheTime.png", width = 480, height = 480)
par(mar = c(5, 6, 0.1, 0.1))
plot(c(1, ncol(xi)), range(xi), log = 'y', type = 'n',
     xlab = "Days", ylab = "", las = 1,
     cex.axis = 2, cex.lab = 2, tcl = 0.5)
mtext("Abundance", side = 2, line = 4.5, cex = 2)
lines(xi[1, ], lwd = 2)
lines(xi[2, ], lty = 2, lwd = 2)
lines(xi[3, ], lty = 3, lwd = 2)
points(rep(ncol(xi), 3), x.bar, pch = 21, cex = 1.3, bg = "white") # overall average
legend('bottomright', bty = 'n',
       lty = 1:3, lwd = rep(2, 3),
       legend = c("Aa", "Ac", "Ag"), 
       cex = 2)
dev.off()

## ternary plot ----------------------------------------------------------------

# plots use Ternary package
library(Ternary)

# response functions use global vars
FuncP <- function(a, b, c) {
  Jint <- Jpfun(b, c, A)
  abs.eigs <- abs(eigen(Jint)$values)
  max(abs.eigs)
}

pts <- expand.grid(a = seq(0.01, 0.99, len = 101),
                   b = seq(0.01, 0.99, len = 101))
pts <- pts[rowSums(pts) < 1, ]
pts$c <- 1 - rowSums(pts)

tri <- TriangleCentres(resolution = 50L)
tern.xy <- XYToTernary(tri["x", ], tri["y", ])

vP <- numeric(ncol(tern.xy))
for (i in 1:ncol(tern.xy)) {
  vP[i] <- FuncP(tern.xy["a", i], tern.xy["b", i], tern.xy["c", i])
}

png("nicheTernary.png", width = 480*1, height = 480,
    pointsize = 24)
par(mar = rep(0.2, 4))

TernaryPlot(alab = expression(paste("Percentage of  ", italic(An.~arabiensis))),
            blab = expression(paste("Percentage of  ", italic(An.~coluzzii))),
            clab = expression(paste("Percentage of  ", italic(An.~gambiae), "  s.s.")))
mapP <- rbind(x = tri["x", ], y = tri["y", ], z = vP,
              down = tri["triDown", ])
ColourTernary(mapP, spectrum = viridisLite::viridis(256L, alpha = 0.6))

PlotTools::SpectrumLegend(
  "topleft",
  legend = rev(round(seq(min(vP), max(vP), length.out = 4), 3)),
  palette = viridisLite::viridis(256L, alpha = 0.6),
  bty = "n",    # No framing box
  inset = 0.02,
  xpd = NA      # Do not clip at edge of figure
)

# estimate avg equilibrium
TernaryPoints(p.star, pch = 4, cex = 1.7, col = "white")
# estimate min spec rad
TernaryPoints(tern.xy[1:3, which.min(vP)], pch = 1, cex = 1.7, col = "white")

dev.off()

# optimised analysis -----------------------------------------------------------

obj <- function(p23, Ap) {
  Jp <- Jpfun(p23[1], p23[2], Ap)
  max(abs(eigen(Jp)$values))
}

objJ <- function(log.aij, p.bar) {

  aij <- exp(log.aij)
  Amat <- diag(3)
  Amat[lower.tri(Amat)] <- aij
  Amat[upper.tri(Amat)] <- Amat[lower.tri(Amat)]

  rhobar <- obj(p.bar[2:3], Amat)

  if (rhobar < 1) {

    res <- (rhobar - 1)*mean(exp(log.aij))

  } else {

    res <- Inf

  }

  res

}

# grid search
grid.pts <- expand.grid(a = seq(0, 1, len = 101),
                        b = seq(0, 1, len = 101),
                        c = seq(0, 1, len = 101))
grid.pts <- as.matrix(grid.pts)
grid.pts <- cbind(grid.pts, NA)
colnames(grid.pts)[ncol(grid.pts)] <- "res"
summary(grid.pts)

pt <- proc.time()
for (i in 1:nrow(grid.pts)) {
  grid.pts[i, "res"] <- objJ(log(c(grid.pts[i, 1:3])), p.star)
  # print progress:
  # if (i%%1000 == 0) cat('completed ', 100*(i/nrow(grid.pts)), "percent after ", 
  #                       proc.time()[3] - pt[3], "secs \n")
}

ind.maxGrad <- which.min(grid.pts[ , "res"])
grid.pts[ind.maxGrad, ]
maxGrad.coords <- grid.pts[ind.maxGrad, 1:3]

Agrid <- diag(3)
Agrid[lower.tri(Agrid)] <- maxGrad.coords
Agrid[upper.tri(Agrid)] <- Agrid[lower.tri(Agrid)]
round(Agrid, 3)

print(xtable::xtable(Agrid), file = "Agrid.txt")

## simulation ------------------------------------------------------------------

# optimised
A <- Aoptim <- Agrid
q <- diag(z)%*%solve(diag(lambda - z))%*%A%*%x.bar
solve(A)%*%diag(lambda - z)%*%solve(diag(z))%*%q - x.bar

J <- Jfun(x.bar, A)
all.equal(Jfun(x.bar, A), Jpfun(x.bar[2]/sum(x.bar), x.bar[3]/sum(x.bar), A))
summary(abs(eigen(J)$values))

# initial condition: random deviation from overall average from Pianka ex above
xi0

Q <- diag(c(q))
N <- 365
xi.opt <- matrix(NA, nrow = 3, ncol = N)
xi.opt[ , 1:10] <- matrix(xi0, nrow = 10, ncol = 3)
for (tt in 11:N) {
  xi.opt[ , tt] <- diag(sigma)%*%xi.opt[ , tt - 1] + 
    + solve(diag(c(1 + solve(Q)%*%A%*%xi.opt[ , tt - 10])))%*%xi.opt[ , tt - 10]*lambda
}

png("optTime.png", width = 480, height = 480)
par(mar = c(5, 6, 0.1, 0.1))
plot(c(1, ncol(xi.opt)), range(xi), log = 'y', type = 'n',
     xlab = "Days", ylab = "", las = 1,
     cex.axis = 2, cex.lab = 2, tcl = 0.5)
mtext("Abundance", side = 2, line = 4.5, cex = 2)
lines(xi.opt[1, ], lwd = 2)
lines(xi.opt[2, ], lty = 2, lwd = 2)
lines(xi.opt[3, ], lty = 3, lwd = 2)
points(rep(ncol(xi), 3), x.bar, pch = 21, cex = 1.3, bg = "white") # overall average
legend('bottomright', bty = 'n',
       lty = 1:3, lwd = rep(2, 3),
       legend = c("Aa", "Ac", "Ag"), 
       cex = 2)
dev.off()

## plot ------------------------------------------------------------------------

# response functions use global vars
FuncOpt <- function(a, b, c) {
  Jint <- Jpfun(b, c, Aoptim)
  abs.eigs <- abs(eigen(Jint)$values)
  max(abs.eigs)
}

pts <- expand.grid(a = seq(0.01, 0.99, len = 101),
                   b = seq(0.01, 0.99, len = 101))
pts <- pts[rowSums(pts) < 1, ]
pts$c <- 1 - rowSums(pts)

tri <- TriangleCentres(resolution = 50L)
tern.xy <- XYToTernary(tri["x", ], tri["y", ])

vOpt <- numeric(ncol(tern.xy))
for (i in 1:ncol(tern.xy)) {
  vOpt[i] <- FuncOpt(tern.xy["a", i], tern.xy["b", i], tern.xy["c", i])
}

png("optTernary.png", width = 480*1, height = 480, pointsize = 24)
par(mar = rep(0.2, 4))

TernaryPlot(alab = expression(paste("Percentage of  ", italic(An.~arabiensis))),
            blab = expression(paste("Percentage of  ", italic(An.~coluzzii))),
            clab = expression(paste("Percentage of  ", italic(An.~gambiae), "  s.s.")))
mapOpt <- rbind(x = tri["x", ], y = tri["y", ], z = (vOpt),
                down = tri["triDown", ])
ColourTernary(mapOpt, spectrum = viridisLite::viridis(256L, alpha = 0.6))

PlotTools::SpectrumLegend(
  "topleft",
  legend = rev(round(seq(min(vOpt), max(vOpt), length.out = 4), 3)),
  palette = viridisLite::viridis(256L, alpha = 0.6),
  bty = "n",    # No framing box
  inset = 0.02,
  xpd = NA      # Do not clip at edge of figure
)

# estimate avg equilibrium
TernaryPoints(p.star, pch = 4, cex = 1.7, col = "white")
# estimate min spec rad
TernaryPoints(tern.xy[1:3, which.min(vOpt)], pch = 1, cex = 1.7, col = "white")

dev.off()

# plot of deviations

devNiche <- colSums(abs(xi - x.bar))
devOpt <- colSums(abs(xi.opt - x.bar))

png("devTime.png", width = 480, height = 480)
par(mar = c(5, 4, 0.1, 0.1))
plot(c(1, ncol(xi.opt)), range(c(devNiche, devOpt)), type = 'n', log = "y",
     xlab = "Days", ylab = "Absolute Deviation from Equilibrium", las = 1)
lines(devNiche, lwd = 2)
lines(devOpt, lty = 2, lwd = 2)
legend('bottomright', bty = 'n',
       lty = 1:2, lwd = rep(2, 2),
       legend = c("Niche", "Optimised"))
dev.off()


```

